server:
  port: 8080
  tomcat:
    connection-timeout: 1800000
spring:
  config:
    import:
    - classpath:/config/config-server-import.yml
#    - optional:CONFIG_IP
  profiles:
    active: dev
  application:
    name: configuration
  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# jpa
#  jpa:
#    hibernate:
#      ddl-auto: create

# refresh
management:
  endpoints:
    web:
      exposure:
        include: refresh
